os: windows
sudo: required
language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - sudo apt-get install libsfml-dev
  - cmake ..

script: make
notifications:
    email: false